### ISSUE TITLE
Text Bouncing around a lot and looking weird

### ISSUE THREAD

**Issue by arhoy** [braposo/react-text-loop#38] opened 2019-10-21 05:12 UTC
I followed the simple example and the transition effects look weird. There is a lot of bouncing around and the text looping from different directions. Not sure if this is a bug or the intended design. Is there any possible way to dampen this effect and make it come from one direction only in a "plain old boring way"

**Comment by harshil1712** [comment] 2019-10-24 13:12
I am facing the same issue. Instead of having an animation where the text comes from down, it seems to be coming from sides. 
Please let me know if there's a fix for this.
Thank you.

**Comment by arhoy** [comment] 2019-10-24 18:34
Any updates on this? Right now this library is not functional or production ready because of these issues and weird behaviors. Does anyone know of any good alternatives to this library

**Comment by braposo** [comment] 2019-10-25 21:40
Hey @arhoy @harshil1712 do you mind using this sandbox to replicate the issue? https://codesandbox.io/s/react-text-loop-playground-n9cb9

Can't reproduce the behaviour you're seeing in that example 😞 

Thanks!

**Comment by micleners** [comment] 2019-11-16 23:38
I had the same issue, I believe!

I think this happens when all the elements are not equal width.

What I did was set each element's width to 500px and center aligned the text. That fixed it for me 😬I hope this helps!

**Comment by arhoy** [comment] 2019-11-18 10:09
Thanks @micleners . I think it is easier to build my open looping component rather than tinker with the oddities of this library!

**Comment by braposo** [comment] 2019-11-20 01:00
@arhoy you can probably try adding `adjustingSpeed={0}` to the `TextLoop` component to minimise the effect of the wrapper adjustment and/or use `display: block` in each of the elements (or use a div) to give every element the same width as @micleners suggested. 

When you have multiple centered elements that are inline elements (like a span) it requires some adjustment from the wrapper component to be able to display them correctly, causing that sideways movement.

From my experience these issues are usually a consequence of the way that the elements are styled, not so much to do with the library.

**Closed by braposo** 2019-11-20 01:00 UTC

**Comment by abubakir1997** [comment] 2020-09-30 19:29
You just need to assign the transition elements the same width, if your text width is arbitrary give it a large number and it should handle the centering: 

```ts
styled(TextLoop)`
  > div > div {
    width: 1000vw !important; 
  }
`
```
